version: '3.3'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=influx.beenode
      - DOCKER_INFLUXDB_INIT_ORG=beenode 
      - DOCKER_INFLUXDB_INIT_BUCKET=beenodedb
      - DOCKER_INFLUXDB_INIT_RETENTION=4w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=woj7fyAVVC25kaY_YCw6ycRFOPvUR1q7cfd_DfndhEmIK8gmcRPONIojzEFe6Gr7t39uFSKL_43WUHsD5niP-g==

volumes:
    influxdb-storage:
